name: Publish Package

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: 19.x
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.3.1
      - name: Use common from GitHub in CI
        run: jq '.pnpm.overrides["@anupheaus/common"] = "github:Anupheaus/common"' package.json > package.json.tmp && mv package.json.tmp package.json
      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile
      # - name: Run Tests
      #   run: pnpm run test-ci
      - name: Build
        run: pnpm run build
      - name: Perform Version Bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pack
        run: pnpm pack
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"

  Publish:
    needs: [Build]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'anupheaus'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: 19.x
          registry-url: https://npm.pkg.github.com/
          scope: '@anupheaus'
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.3.1
      - name: Publish
        run: pnpm publish $(ls *.tgz) --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
